.

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -19,8 +19,8 @@ jobs:
 
     - name: Create log file
       run: |
-        echo "$(date)" > /tmp/log.txt
-        echo "${{ env.SUBMITTER_NAMES }}" >> /tmp/log.txt
+        echo "Line 1: $(date)" > /tmp/log.txt
+        echo "Line 2: ${{ env.SUBMITTER_NAMES }}" >> /tmp/log.txt
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
@@ -37,9 +37,9 @@ jobs:
     - name: Log success of building image
       run: |
         if [[ ${{ steps.build-and-export.outcome }} == 'success' ]]; then
-          echo "Build Job: image successfully built" >> /tmp/log.txt
+          echo "Line 3: image successfully built" >> /tmp/log.txt
         else
-          echo "Build Job: image not able to be built" >> /tmp/log.txt
+          echo "Line 3: image not able to be built" >> /tmp/log.txt
         fi
 
     - name: Upload image artifact
@@ -48,9 +48,9 @@ jobs:
         name: image_artifact
         path: image.tar
 
-    - name: Logging
-      run: | 
-        echo "Build Job: Uploaded image artifact" >> /tmp/log.txt
+#    - name: Logging
+#      run: |
+#        echo "Build Job: Uploaded image artifact" >> /tmp/log.txt
 
     - name: Upload log artifact
       uses: actions/upload-artifact@v3
@@ -80,17 +80,17 @@ jobs:
     - name: Load Docker image
       run: docker load --input image_artifact/image.tar
 
-    - name: Logging
-      run: | 
-        echo "Test Job: Loaded Docker image" >> /tmp/log.txt
+#    - name: Logging
+#      run: |
+#        echo "Test Job: Loaded Docker image" >> /tmp/log.txt
 
     - name: Run Docker image in container
       run: |
         docker run --rm -d -p 8000:8000 meals:latest
         if [ $? -eq 0 ]; then
-          echo "Test Job: Container up and running" >> /tmp/log.txt
+          echo "Line 4: container up and running" >> /tmp/log.txt
         else
-          echo "Test Job: Container failed to run" >> /tmp/log.txt
+          echo "Line 4: container failed to run" >> /tmp/log.txt
         fi
 
     - name: Checkout
@@ -110,9 +110,13 @@ jobs:
       run: |
         pytest -v tests/assn3_tests.py > assn3_test_results.txt
 
-    - name: Logging
+    - name: Log success of tests
       run: | 
-        echo "Test Job: Tests succeeded" >> /tmp/log.txt
+        if [ $? -eq 0 ]; then
+          echo "Line 5: tests succeeded" >> /tmp/log.txt
+        else
+          echo "Line 5: tests failed" >> /tmp/log.txt
+        fi
 
     - name: Upload test results
       if: always()  # always perform this step even if tests fail, to see results
